#!/usr/bin/env bash

DIR_NAME=$1
EXTENSION="cc"

# Use the user-provided extension if it exists.
if [ $# -gt 1 ]; then
    EXTENSION=$2
fi

# The directory holding all the template directories.
TEMPLATES_DIR=$(dirname $(realpath $0))/cfinit-templates
# The selected template directory.
TEMPLATE=$TEMPLATES_DIR/$EXTENSION-template

# Don't override an existing directory.
if [ -d $DIR_NAME ]; then
    echo "The directory already exists. Aborting..."
    exit -1
fi

# Copy the template.
cp -r $TEMPLATE $DIR_NAME
